---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r}
instacartdf = instacart  %>%
   filter(aisle %in% c("baking ingredients", "dog food care", "packaged vegetables fruits")) 
```

Column {data-width=650}
-----------------------------------------------------------------------
```{r}
instacart_df2 = instacart %>%
  
  filter(department %in% c("frozen", "produce", "deli")) %>%
  group_by(aisle, order_hour_of_day, department, order_dow) %>% 
  count(department) %>% 
    filter(n < 400, n > 0) %>% 
  rename(department_count = n) 
```


### Chart A

```{r}
    instacart_df2 %>%
plot_ly(y = ~department_count, x = ~order_hour_of_day, type = "scatter", mode = "markers", color=~department, alpha = 0.5, colors = "viridis")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
instacartdf %>% 
  mutate(department = fct_reorder(department, days_since_prior_order)) %>% 

  plot_ly(y = ~days_since_prior_order, color = ~department, type = "box", colors = "viridis")
```

### Chart C

```{r}
instacartdf %>% 
  count(department) %>% 

  mutate(department = fct_reorder(department, n)) %>% 
  plot_ly(x = ~department, y = ~n, color = ~department, type = "bar", colors = "viridis")
```

